spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phonebook
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

server:
  port: 8091

paths:
  prepare: .prepare
  work: .work
  data: .data
  log: .log
  logFile: log.txt